//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.AdminSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ProductImageID { get; set; }
        public string ImageDescription { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<bool> ImageActive { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
