//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreWebAPI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductModel { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string ProductKeywords { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> ProductActive { get; set; }
        public Nullable<System.DateTime> ProductCreateDateTime { get; set; }
        public Nullable<System.DateTime> ProductUpdateDateTime { get; set; }
    }
}
